// export const projects = {
// 	headline: 'Patrick Mahomes E-Commerce',
// 	description: 'Clone of the Patrick Mahomes online store.',
// 	img: '/images/PatMahomes.png',
// 	tags: ['React JS', 'CSS/Sass', 'FireBase'],
// 	source: 'https://github.com/urreita9/PatMahomesEcommerceClone__coderHouse',
// 	visit: 'https://patmahomes-store-coderhouse.web.app/',
// 	id: 0,
// 	lightBg: false,
// 	lightText: true,
// 	lightTextDesc: true,
// 	topline: 'CoderHouse',
// 	buttonLabel1: 'Visit',
// 	buttonLabel2: '< />',
// 	imgStart: false,
// 	alt: 'Patrick Mahomes E-Commerce',
// 	dark: true,
// 	primary: true,
// 	darkText: false,
// };

export const projects = [
	{
		headline: 'Pokemon App',
		description: 'Search, store and create your own Pokemons!',
		img: './images/screenShot_home.png',
		tags: ['React', 'Redux', 'Sass', 'Node/Express', 'PostgreSQL', 'Sequelize'],
		source: 'https://github.com/urreita9/PI-POKEMON',
		visit: 'https://pi-pokemon-topaz.vercel.app/',
		id: 0,
		lightBg: false,
		lightText: true,
		lightTextDesc: true,
		topline: 'Soy Henry Bootcamp',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: false,
		alt: 'Pokemon App',
		dark: true,
		primary: true,
		darkText: false,
	},

	{
		headline: 'Patrick Mahomes E-Commerce',
		description: 'Clone of the Patrick Mahomes online store.',
		img: './images/PatMahomes.png',
		tags: ['React JS', 'CSS/Sass', 'FireBase'],
		source: 'https://github.com/urreita9/PatMahomesEcommerceClone__coderHouse',
		visit: 'https://patmahomes-store-coderhouse.web.app/',
		id: 1,
		lightBg: true,
		lightText: false,
		lightTextDesc: false,
		topline: 'CoderHouse',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: true,
		alt: 'Patrick Mahomes E-Commerce',
		dark: false,
		primary: false,
		darkText: true,
	},
	//
	{
		headline: 'Giphos App',
		description: 'Search, store and make your own GIFOS!',
		img: './images/giphosApp.png',
		tags: ['HTML', 'CSS/Sass', 'JavaScript'],
		source: 'https://github.com/urreita9/giphos',
		visit: 'https://urreita9.github.io/giphos/',
		id: 2,
		lightBg: false,
		lightText: true,
		lightTextDesc: true,
		topline: 'Acamica Dev School',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: false,
		alt: 'Giphos App',
		dark: true,
		primary: true,
		darkText: false,
	},
	{
		headline: 'ToDo App',
		description:
			'Great App to write your Todos. Saved in localStorage. Drag n Drop em!',
		img: './images/ToDoApp.png',
		tags: ['React', 'Javascript'],
		source: 'https://github.com/urreita9/todo-app',
		visit: 'https://todo-app-eight-xi.vercel.app/',
		id: 3,
		lightBg: true,
		lightText: false,
		lightTextDesc: false,
		topline: 'FrontEnd Mentor',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: true,
		alt: 'ToDo App',
		dark: false,
		primary: false,
		darkText: true,
	},
	{
		headline: 'Tip Calculator',
		description: 'Add up with your friends and calculate tips.',
		img: './images/TipCalculatorApp.png',
		tags: ['React', 'CSS/Sass'],
		source: 'https://github.com/urreita9/tip-calculator-app',
		visit: 'https://tip-calculator-app-nine.vercel.app/',
		id: 4,
		lightBg: false,
		lightText: true,
		lightTextDesc: true,
		topline: 'FrontEnd Mentor',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: false,
		alt: 'Tip Calculator',
		dark: true,
		primary: true,
		darkText: false,
	},

	{
		headline: 'Rock, Paper, Sciossors!',
		description: 'Challenge the AI to a rock, paper, scissors game!',
		img: './images/RockPaperScissors.png',
		tags: ['React', 'CSS/Sass'],
		source: 'https://github.com/urreita9/rock-paper-scissors-game',
		visit: 'https://rock-paper-scissors-game-urreita9.vercel.app/',
		id: 5,
		lightBg: true,
		lightText: false,
		lightTextDesc: false,
		topline: 'FrontEnd Mentor',
		buttonLabel1: 'Visit',
		buttonLabel2: '< />',
		imgStart: true,
		alt: 'Rock, Paper, Sciossors!',
		dark: false,
		primary: false,
		darkText: true,
	},
];
